spring:
  datasource:
    url: jdbc:postgresql://localhost:${CART_DB_PORT}/${CART_DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
logging:
  level:
    org:
      hibernate:
        SQL: debug