spring:
  cloud:
    config:
      label: services
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
  config:
    import: "optional:configserver:"

  mail:
    from: noreply@gmail.com
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER_USERNAME}
    password: ${EMAIL_SENDER_PASSWORD}