spring:
  cloud:
    config:
      label: services
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
  config:
    import: "optional:configserver:"

  grpc:
    client:
      channels:
        product-service:
          address: 0.0.0.0:1013
        profile-service:
          address: 0.0.0.0:2020
    server:
     port: 1016

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: false
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual_immediate
  pulsar:
    consumer:
      retry-enable: true

resilience4j:
  circuitbreaker:
    instances:
      product-service:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 10
        sliding-window-size: 50
        register-health-indicator: true